services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apollo-auto
      MYSQL_USER: apollo-auto
      MYSQL_PASSWORD: apollo-auto-password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: apollo-auto
      PMA_PASSWORD: apollo-auto-password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
